/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-07-07 10:28:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import model.bean.Tree;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpServletRequest;

public final class modificaAlberi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/admin/admin.jsp", Long.valueOf(1657179766000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("model.bean.Tree");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Arbor Vitae Admin</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	 ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js\"\n");
      out.write("	integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"js/jquery-ui-1.13.1.custom/jquery-ui.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"js/jquery-ui-1.13.1.custom/jquery-ui.min.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\n");
      out.write("			<ul class=\"navbar-nav\">\n");
      out.write("				<li class=\"nav-item active\"><a class=\"nav-link\"\n");
      out.write("					href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/admin.jsp\">Home\n");
      out.write("						<span class=\"sr-only\">(current)</span>\n");
      out.write("				</a></li>\n");
      out.write("				<li class=\"nav-item dropdown\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\"\n");
      out.write("					id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\"\n");
      out.write("					aria-haspopup=\"true\" aria-expanded=\"false\">Visualizza</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"/ArborVitae/gestione?id=");
      out.print(1);
      out.write("\">Admin</a>\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"/ArborVitae/gestione?id=");
      out.print(2);
      out.write("\">Utenti</a>\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"/ArborVitae/gestione?id=");
      out.print(3);
      out.write("\">Alberi</a>\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"/ArborVitae/gestione?id=");
      out.print(4);
      out.write("\">Ordini</a>\n");
      out.write("					</div></li>\n");
      out.write("				<li class=\"nav-item dropdown\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\"\n");
      out.write("					id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\"\n");
      out.write("					aria-haspopup=\"true\" aria-expanded=\"false\">Aggiungi</a>\n");
      out.write("					<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/aggiungiAdmin.jsp\">Admin</a>   <!-- id=5 -->\n");
      out.write("						<a class=\"dropdown-item\"\n");
      out.write("							href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/aggiungiAlberi.jsp\">Alberi</a>\n");
      out.write("					</div></li>\n");
      out.write("					<li class=\"nav-item active\"><a class=\"nav-link\" href=\"/ArborVitae/logout\">Logout</a>\n");
      out.write("       				 </li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	 \n");
      out.write("	 <h2>Modifica alberi</h2>\n");
      out.write("	 <br>\n");
      out.write("	 ");
if(session.getAttribute("albero")!=null){ 
      out.write("\n");
      out.write("	 	");
ArrayList<Tree>lista=(ArrayList<Tree>)session.getAttribute("albero"); 
      out.write("\n");
      out.write("	 	");
Tree t = lista.get(0); 
      out.write("\n");
      out.write("	 	<table>\n");
      out.write("	 	<tr>\n");
      out.write("	 		<th>Nome</th>\n");
      out.write("	 		<td scope=\"col\">");
      out.print(t.getName());
      out.write("</td>\n");
      out.write("	 	</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>Specie</th>\n");
      out.write("			<td scope=\"col\">");
      out.print(t.getSpecies());
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>Country</th>\n");
      out.write("			<td scope=\"col\">");
      out.print(t.getCountry());
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>CO2</th>\n");
      out.write("			<td scope=\"col\">");
      out.print(t.getCo2());
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>Descrizione</th>\n");
      out.write("			<td scope=\"col\">");
      out.print(t.getDescription());
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<th>Prezzo</th>\n");
      out.write("			<td scope=\"col\">");
      out.print(t.getPrice());
      out.write("</td>\n");
      out.write("		</tr>\n");
      out.write("		</table>\n");
      out.write("		<br>	\n");
      out.write("	 <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gestione?id=");
      out.print(11);
      out.write("&name=");
      out.print(t.getName());
      out.write("\" method=\"post\">\n");
      out.write("		<table align=\"center\">\n");
      out.write("		<tr><td width=\"50%\">\n");
      out.write("			  	<div class=\"form-group\">\n");
      out.write("				    <label for=\"exampleFormControlInput1\">Modifica descrizione</label>\n");
      out.write("				    <input type=\"text\" name=\"newDes\" class=\"form-control\">\n");
      out.write("			  	</div>\n");
      out.write("		</td></tr>\n");
      out.write("		<tr><td width=\"50%\">\n");
      out.write("			  	<div class=\"form-group\">\n");
      out.write("				    <label for=\"exampleFormControlInput1\">Modifica prezzo</label>\n");
      out.write("				    <input type=\"text\" name=\"newPrice\" class=\"form-control\" placeholder=\"\">\n");
      out.write("			  	</div>\n");
      out.write("		</td></tr>\n");
      out.write("		<tr><td width=\"50%\">\n");
      out.write("			  	<div class=\"form-group\">\n");
      out.write("				   <button type=\"submit\" class=\"btn login_btn\">Modifica</button>\n");
      out.write("			  	</div>\n");
      out.write("		</td></tr>\n");
      out.write("		\n");
      out.write("		</table>\n");
      out.write("	</form>\n");
      out.write("	 ");
} 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
