/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-07-07 10:27:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.dao.ShoppingCartDao;
import java.util.ArrayList;
import model.bean.Tree;
import model.bean.ShoppingCart;
import model.bean.ShoppingCart;
import model.dao.ShoppingCartDao;
import java.util.ArrayList;
import model.bean.Tree;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/html/homeNavbar.jsp", Long.valueOf(1657099948000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.Tree");
    _jspx_imports_classes.add("model.bean.ShoppingCart");
    _jspx_imports_classes.add("model.dao.ShoppingCartDao");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write(" <html>\n");
      out.write(" <head>\n");
      out.write("  <meta charset=\"ISO-8859-1\">\n");
      out.write("  <title>Arbor Vitae</title>\n");
      out.write("  <link rel=\"icon\" href=\"/ArborVitae/img/homepage_images/logo.ico\" type=\"image/x-icon\">\n");
      out.write("  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/cart.css\">\n");
      out.write(" </head>\n");
      out.write(" \n");
      out.write(" <style>\n");
      out.write("  .cart-elements-count{\n");
      out.write("   top: 12px;\n");
      out.write("      right: 10px !important;\n");
      out.write("  }\n");
      out.write(" </style>\n");
      out.write(" <body>\n");
      out.write(" <script>\n");
      out.write("  function add(x){\n");
      out.write("        var quantityDiv=document.getElementById(x);\n");
      out.write("        quantityDiv.innerHtml=(parseInt(quantityDiv.innerHtml)+1).toString();\n");
      out.write("  }\n");
      out.write(" \n");
      out.write("</script>\n");
      out.write(" ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>Arbor Vitae</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"/ArborVitae/style/homepage.css\">\n");
      out.write("  <style>\n");
      out.write("    .cart-button{\n");
      out.write("      border: none;\n");
      out.write("      background-color: white;\n");
      out.write("      padding: 0px !important;\n");
      out.write("    }\n");
      out.write("      \n");
      out.write("    .profile-button{\n");
      out.write("      border: none;\n");
      out.write("      background-color: white;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("   .dropbtn {\n");
      out.write("    background-color: none !important;\n");
      out.write("    color: white;\n");
      out.write("    padding: 8px;\n");
      out.write("    font-size: 10px;\n");
      out.write("    border: none;\n");
      out.write("    float: right;\n");
      out.write("    margin: -5px 0px 3px 0px;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown {\n");
      out.write("     position: relative;\n");
      out.write("     display: inline-block;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content {\n");
      out.write("     display: none;\n");
      out.write("     position: absolute;\n");
      out.write("     background-color: white;\n");
      out.write("     min-width: 160px;\n");
      out.write("     box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("     z-index: 1;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content a {\n");
      out.write("     color: gray;\n");
      out.write("     padding: 3.5px;\n");
      out.write("     text-decoration: none;\n");
      out.write("     display: block;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content a:hover {background-color: #ddd; border-radius: 10px}\n");
      out.write("   \n");
      out.write("   .dropdown:hover .dropdown-content {display: block; border-radius: 10px}\n");
      out.write("   \n");
      out.write("   .dropdown:hover .dropbtn {background-color: #46dd2c; border-radius: 10px}\n");
      out.write("   \n");
      out.write("  </style>\n");
      out.write(" </head>\n");
      out.write(" \n");
      out.write(" <body>\n");
      out.write("  <header>\n");
      out.write("   <div class=\"logo\">\n");
      out.write("    <div class=\"navbar-item img-navbar-item\">\n");
      out.write("     <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/homepage_images/logo.png\" alt=\"Arbor Vitae's logo\" />\n");
      out.write("    </div>\n");
      out.write("    <div class=\"navbar-item\">\n");
      out.write("     <h1 class=\"site-title\"> Arbor Vitae</h1>\n");
      out.write("    </div>\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("   <input type=\"checkbox\" id=\"nav-toggle\" class=\"nav-toggle\">\n");
      out.write("   \n");
      out.write("   <nav>\n");
      out.write("   <div>\n");
      out.write("    <ul>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp\" class=\"link-elements\">Home</a></li>\n");
      out.write("    <li><a href=\"/ArborVitae/catalogoServlet?ordinamento=");
      out.print(1);
      out.write("\" class=\"link-elements\">Catalogo</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp#project\" class=\"link-elements\">Progetto</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp#aboutus\" class=\"link-elements\">Team</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp#footer\" class=\"link-elements\">Contatti</a></li>\n");
      out.write("   \n");
      out.write("    \n");
      out.write("    ");
 if(request.getSession(false)==null || session.getAttribute("logged")==null || session.getAttribute("logged").equals("false")){
      out.write("\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/login.jsp\"><button type=\"button\" class=\"login-signup-buttons\">Login</button></a></li>\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/signup.jsp\"><button type=\"button\" class=\"login-signup-buttons\">Sign Up</button></a></li>\n");
      out.write("       ");
}else{
      out.write("\n");
      out.write("        <li id=\"prev-count\"><a href=\"/ArborVitae/view/cart.jsp\"><button type=\"button\" class=\"cart-button\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/homepage_images/cart.png\" width=\"45px\" height= \"45px\"></button></a></li>\n");
      out.write("        ");
 ShoppingCartDao scd=new ShoppingCartDao();
         ShoppingCart sc= scd.doRetrieveByKey((String)session.getAttribute("email"));
         if(sc!=null){
          ArrayList<Tree> list= scd.doRetrieveTrees(sc.getcodeCart());
          if(list!=null){ 
           int x=list.size();
           if(x>0){
      out.write("\n");
      out.write("            <li><p class=\"cart-elements-count\" id=\"count\">");
      out.print(x);
      out.write("</p></li>\n");
      out.write("           ");
}
      out.write("\n");
      out.write("          ");
}
      out.write("\n");
      out.write("       ");
}
      out.write("\n");
      out.write("     <li><div class=\"dropdown\">\n");
      out.write("          \n");
      out.write("           <button type=\"button\" class=\"profile-button dropbtn\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/homepage_images/profile.png\" width=\"35px\" height=\"35px\">\n");
      out.write("            <div class=\"dropdown-content\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/ordini.jsp\">I miei Ordini</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" >Log out</a>\n");
      out.write("        </div>\n");
      out.write("           </button>\n");
      out.write("      \n");
      out.write("         </div></li>\n");
      out.write("   ");
}
      out.write("\n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("   </div>\n");
      out.write("   </nav>\n");
      out.write("   \n");
      out.write("   <label for=\"nav-toggle\" class=\"nav-toggle-label\">\n");
      out.write("    <span></span>\n");
      out.write("   </label>\n");
      out.write("\n");
      out.write("  </header>\n");
      out.write(" </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("  <div class=\"cart_section\">\n");
      out.write("     <div class=\"container-fluid\" id=\"container-fluid\">\n");
      out.write("         <div class=\"row\">\n");
      out.write("             <div class=\"col-lg-10 offset-lg-1\">\n");
      out.write("                 <div class=\"cart_container\">\n");
      out.write("                     <div class=\"cart_title\">Carrello</div>\n");
      out.write("                     <div class=\"cart_items\" id=\"cart_items\">\n");
      out.write("                         <ul class=\"cart_list\" id=\"cart_list\">\n");
      out.write("                           ");
 ShoppingCartDao scd= new ShoppingCartDao();
                              ShoppingCart sc=scd.doRetrieveByKey((String)session.getAttribute("email"));
                           if(sc!=null) {
      out.write("\n");
      out.write("                           \n");
      out.write("                           ");
ArrayList<Tree> list= scd.doRetrieveTrees(sc.getcodeCart());
                            if(list.size()>0){
                             int i=0;
                             int j;
                             double sum=0;
                             for(i=0;i<list.size();i++){
                            	int count=1;  
                            	Tree currentTree=list.get(i);
                              	for(j=i+1;j<list.size();j++){
                              		if(list.get(i).getName().equals(list.get(j).getName())){
                                		list.remove(j);
                                		j--;
                                 		count++;
                              		}
                              }
      out.write("\n");
      out.write("                             	<div>\n");
      out.write("                             	 <li class=\"cart_item clearfix\">\n");
      out.write("                                 <div class=\"cart_item_image\"><img src=\"/ArborVitae/img/trees_img/");
      out.print(currentTree.getName().toLowerCase()+"1.jpg");
      out.write("\" alt=\"\"></img></div>\n");
      out.write("                                   <div class=\"cart_item_info d-flex flex-md-row flex-column justify-content-between\">\n");
      out.write("                                       <div class=\"cart_item_name cart_info_col\">\n");
      out.write("                                            <div class=\"cart_item_title\">Nome</div>\n");
      out.write("                                             <div class=\"cart_item_text\">");
      out.print(currentTree.getName());
      out.write("</div>\n");
      out.write("                                       </div>\n");
      out.write("                                       <div class=\"cart_item_quantity cart_info_col\">\n");
      out.write("                                           <div class=\"cart_item_title\">Quantita'</div>\n");
      out.write("                                           <div class=\"cart_item_text\" id=\"");
      out.print(i );
      out.write("\">\n");
      out.write("                                           		<p class=item_Quant>");
      out.print(count );
      out.write("</p>\n");
      out.write("                                           		<button class=\"inc_Dec\" onclick=\"increase(this)\">+</button>\n");
      out.write("                                          	 	<button class=\"inc_Dec\" onclick=\"decrease(this)\">-</button>\n");
      out.write("                                       	   </div>\n");
      out.write("                                       </div>\n");
      out.write("                                       <div class=\"cart_item_price cart_info_col\">\n");
      out.write("                                           <div class=\"cart_item_title\">Prezzo</div>\n");
      out.write("                                           <div class=\"cart_item_text\">\n");
      out.write("                                           <p class=\"item_Quant3\">");
      out.print( String.format("%.2f", currentTree.getPrice()).replace(',', '.') );
      out.write("</p>\n");
      out.write("                                           <p class=\"item_Quant4\"> &euro;</p>\n");
      out.write("                                           <p class=\"to_be_hidden\">");
      out.print( String.format("%.2f", currentTree.getPrice()).replace(',', '.') );
      out.write("</p>\n");
      out.write("                                      </div>\n");
      out.write("                                      </div>\n");
      out.write("                                   </div>\n");
      out.write("                               </li>\n");
      out.write("                               ");
if(i+1!=list.size()){
      out.write("\n");
      out.write("                            		   <div id=\"hor_line\"><hr></div>\n");
      out.write("                               ");
}
      out.write("\n");
      out.write("                             ");
 sum=sum+(count*list.get(i).getPrice());
      out.write("\n");
      out.write("                           	</div>\n");
      out.write("                           ");
}
      out.write("\n");
      out.write("                         </ul>\n");
      out.write("                     </div>\n");
      out.write("                     <div id=\"totalContainer\">\n");
      out.write("                     	<div class=\"order_total\">\n");
      out.write("                         <div class=\"order_total_content text-md-right\">\n");
      out.write("                             <div class=\"order_total_title\">Totale:</div>\n");
      out.write("\n");
      out.write("					<div class=\"order_total_amount\" id=\"order_total_amount\">\n");
      out.write("						<p class=\"item_Quant3\">");
      out.print( String.format("%.2f",sum).replace(',', '.') );
      out.write("</p>\n");
      out.write("						<p class=\"item_Quant4\"> &euro;</p>\n");
      out.write("					</div>\n");
      out.write("                         </div>\n");
      out.write("                     </div>\n");
      out.write("                     <div class=\"cart_buttons\"> <button type=\"button\" onclick=\"redirect()\" class=\"button cart_button_clear\">Continue Shopping</button> <button type=\"button\" class=\"button cart_button_checkout\" onclick=\"addToOrders()\">Proceed to Checkout</button> </div>\n");
      out.write("                	</div>	\n");
      out.write("                	<script>\n");
      out.write("                		function redirect(){\n");
      out.write("                			window.location.replace(\"http://localhost:8080/ArborVitae/catalogoServlet?ordinamento=1\");\n");
      out.write("                	 	}	\n");
      out.write("                		\n");
      out.write("                		function increase(x){\n");
      out.write("                			let y = x.parentElement.firstElementChild;\n");
      out.write("                			let calc=parseInt(y.innerHTML);\n");
      out.write("                			calc=calc+1;\n");
      out.write("                			y.innerHTML=\"\"+calc;\n");
      out.write("                			let priceDiv = x.parentElement.parentElement.nextElementSibling.firstElementChild.nextElementSibling.firstElementChild;\n");
      out.write("                			let pr=parseFloat(priceDiv.nextElementSibling.nextElementSibling.innerHTML.replace(',','.'));\n");
      out.write("                			let priceConst=priceDiv.nextElementSibling.nextElementSibling;\n");
      out.write("                			if(calc==1){\n");
      out.write("                				let z = document.getElementById(\"order_total_amount\");\n");
      out.write("                				let m=parseFloat(z.firstElementChild.innerHTML).toFixed(2);\n");
      out.write("                				pr=pr.toFixed(2);\n");
      out.write("                				m=Number(m)+Number(parseFloat(priceConst.innerHTML).toFixed(2));\n");
      out.write("                				z.innerHTML= \"\"+m.toFixed(2);\n");
      out.write("                				let xhrObj=new XMLHttpRequest();\n");
      out.write("                				let TreeName=x.parentElement.parentElement.previousElementSibling.firstElementChild.nextElementSibling;\n");
      out.write("                				xhrObj.open(\"GET\",\"/ArborVitae/shoppingCartServlet?treeName=\"+TreeName.innerHTML,true);\n");
      out.write("                				xhrObj.send();\n");
      out.write("                				return;\n");
      out.write("                			}\n");
      out.write("                			pr = parseFloat(priceDiv.innerHTML.replace(',','.'));\n");
      out.write("                			pr= pr.toFixed(2);\n");
      out.write("                			let z = document.getElementById(\"order_total_amount\");\n");
      out.write("                			let m = parseFloat(z.firstElementChild.innerHTML).toFixed(2);\n");
      out.write("                			m=Number(m) + Number(parseFloat(priceConst.innerHTML).toFixed(2));\n");
      out.write("                			m=m.toFixed(2);\n");
      out.write("            				z.firstElementChild.innerHTML= \"\"+m;\n");
      out.write("                			let xhrObj=new XMLHttpRequest();\n");
      out.write("                			let TreeName=x.parentElement.parentElement.previousElementSibling.firstElementChild.nextElementSibling;\n");
      out.write("                			xhrObj.open(\"GET\",\"/ArborVitae/shoppingCartServlet?treeName=\"+encodeURIComponent(TreeName.innerHTML),true);\n");
      out.write("                			xhrObj.send();\n");
      out.write("                			let g = document.querySelector(\"#count\");\n");
      out.write("                 		    let listCount=g.parentElement;\n");
      out.write("       		   		   	    g.innerHTML=\"\"+(parseInt(g.innerHTML)+1);\n");
      out.write("                 		    	\n");
      out.write("                		}\n");
      out.write("                		\n");
      out.write("                		function decrease(x){\n");
      out.write("                			let y = x.parentElement.firstElementChild;\n");
      out.write("                			let calc=parseInt(y.innerHTML);\n");
      out.write("                			if(calc==0) return;\n");
      out.write("                			calc=calc-1;\n");
      out.write("                			y.innerHTML=\"\"+calc;\n");
      out.write("                			let priceDiv=x.parentElement.parentElement.nextElementSibling.firstElementChild.nextElementSibling.firstElementChild;\n");
      out.write("                			let pr=parseFloat(priceDiv.innerHTML);\n");
      out.write("                			let priceConst=priceDiv.nextElementSibling.nextElementSibling;\n");
      out.write("                			pr=pr.toFixed(2);\n");
      out.write("                			let z = document.getElementById(\"order_total_amount\");\n");
      out.write("                			let m=parseFloat(z.firstElementChild.innerHTML).toFixed(2);\n");
      out.write("                			m=m-parseFloat(priceConst.innerHTML).toFixed(2);\n");
      out.write("                			m=m.toFixed(2);\n");
      out.write("                			z.firstElementChild.innerHTML= \"\"+m;\n");
      out.write("                			let xhrObj=new XMLHttpRequest();\n");
      out.write("                			let TreeName=x.parentElement.parentElement.previousElementSibling.firstElementChild.nextElementSibling;\n");
      out.write("                			xhrObj.open(\"GET\",\"/ArborVitae/shoppingCartServlet?tRemove=\"+encodeURIComponent(TreeName.innerHTML),true);\n");
      out.write("                			xhrObj.send();\n");
      out.write("                			if(calc==0){\n");
      out.write("                				let listElement = x.parentElement.parentElement.parentElement.parentElement.parentElement;\n");
      out.write("            					while((listElement.firstElementChild)!=null){\n");
      out.write("            						listElement.removeChild(listElement.firstElementChild);\n");
      out.write("            					}\n");
      out.write(" 								let ul=listElement.parentElement;\n");
      out.write("            					listElement.parentElement.removeChild(listElement);\n");
      out.write("            					let firstDivChild=ul.firstElementChild;\n");
      out.write("            					if(firstDivChild==(ul.lastElementChild)){\n");
      out.write("            						let elem=document.getElementById(\"hor_line\");\n");
      out.write("            						if(elem!=null){\n");
      out.write("            							elem.parentElement.removeChild(elem);\n");
      out.write("            						}\n");
      out.write("            					}\n");
      out.write("            						\n");
      out.write("            					\n");
      out.write("                			}\n");
      out.write("                			let g = document.querySelector(\"#count\");\n");
      out.write("                 		    let listCount=y.parentElement;\n");
      out.write("                 		 	if((g.innerHTML)=='1'){\n");
      out.write("                				let totalDiv=document.getElementById(\"totalContainer\");\n");
      out.write("                				while((totalDiv.firstElementChild)!=null){\n");
      out.write("                    				totalDiv.removeChild(totalDiv.firstElementChild);\n");
      out.write("                    			}\n");
      out.write("                    			totalDiv.parentElement.removeChild(totalDiv);\n");
      out.write("                 		   		g.parentElement.removeChild(g);\n");
      out.write("                 		    	listCount.parentElement.removeChild(listCount);  \n");
      out.write("                 		     	let f_textEl=document.createElement(\"p\");\n");
      out.write("                 		     	f_textEl.setAttribute(\"id\",\"f-text\");\n");
      out.write("                 		     	f_textEl.classList.add(\"f-text\");\n");
      out.write("                 		     	f_textEl.innerHTML=\"Non hai inserito alcun elemento nel tuo carrello\";\n");
      out.write("                 		     	let contFl=document.getElementById(\"cart_list\");\n");
      out.write("                 		     	contFl.insertBefore(f_textEl,null);	\n");
      out.write("                 		    	return;\n");
      out.write("                 		     }else{\n");
      out.write("                 		      	g.innerHTML=\"\"+(parseInt(g.innerHTML)-1);\n");
      out.write("                 		     }	\n");
      out.write("                 		     \n");
      out.write("                		}\n");
      out.write("                		\n");
      out.write("                		\n");
      out.write("                		function addToOrders(){\n");
      out.write("                			let ernesto = new XMLHttpRequest();\n");
      out.write("                			ernesto.onreadystatechange= function(){\n");
      out.write("                				if(this.readyState==4 && this.status==200){\n");
      out.write("                					let totalDiv=document.getElementById(\"cart_list\");\n");
      out.write("                    				while((totalDiv.firstElementChild)!=null){\n");
      out.write("                        				totalDiv.removeChild(totalDiv.firstElementChild);\n");
      out.write("                        			} \n");
      out.write("                     		     	let f_textEl=document.createElement(\"p\");\n");
      out.write("                     		     	f_textEl.setAttribute(\"id\",\"f-text\");\n");
      out.write("                     		     	f_textEl.classList.add(\"f-text\");\n");
      out.write("                     		     	f_textEl.innerHTML=\"Non hai inserito alcun elemento nel tuo carrello\";\n");
      out.write("                     		     	totalDiv.insertBefore(f_textEl,null);	\n");
      out.write("                					let totCont=document.getElementById(\"totalContainer\");\n");
      out.write("                					while((totCont.firstElementChild)!=null){\n");
      out.write("                        				totCont.removeChild(totCont.firstElementChild);\n");
      out.write("                        			} \n");
      out.write("                					\n");
      out.write("                					totCont.parentElement.removeChild(totCont);\n");
      out.write("                					let g = document.querySelector(\"#count\");\n");
      out.write("                					g.parentElement.removeChild(g);\n");
      out.write("                					\n");
      out.write("                				}\n");
      out.write("                			}\n");
      out.write("                			ernesto.open(\"GET\",\"/ArborVitae/insertOrderServlet\",true);\n");
      out.write("                			ernesto.send();\n");
      out.write("                		}\n");
      out.write("                	</script>	\n");
      out.write("                		\n");
      out.write("                 </div>\n");
      out.write("             </div>\n");
      out.write("         </div>\n");
      out.write("         ");
}else{ 
      out.write("\n");
      out.write("         <p class=\"f-text\" id=\"f-text\">Non hai inserito alcun elemento nel tuo carrello</p>\n");
      out.write("         ");
}}
      out.write("\n");
      out.write("     </div>\n");
      out.write(" </div>\n");
      out.write(" </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
