/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-07-07 09:23:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("  <html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"ISO-8859-1\">\n");
      out.write("    <title>Arbor Vitae</title>\n");
      out.write("     <link rel=\"icon\" href=\"/ArborVitae/img/homepage_images/logo.ico\" type=\"image/x-icon\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"js/jquery-ui-1.13.1.custom/jquery-ui.min.js\"></script>\n");
      out.write("	<link rel=\"stylesheet\" href=\"js/jquery-ui-1.13.1.custom/jquery-ui.min.css\">\n");
      out.write("    <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("    <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.1/css/all.css\" integrity=\"sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP\" crossorigin=\"anonymous\">\n");
      out.write("    <style>\n");
      out.write("      body,html {\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("      height: 100%;\n");
      out.write("	}\n");
      out.write("    \n");
      out.write("    body{\n");
      out.write("		background-image: url('/ArborVitae/img/homepage_images/sfondo.jpg');\n");
      out.write("		background-repeat: no-repeat;\n");
      out.write("		background-size: cover;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    p.pError{\n");
      out.write("   		text-align:center;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .user_card {\n");
      out.write("      height: 450px;\n");
      out.write("      width: 400px;\n");
      out.write("      margin-top: auto;\n");
      out.write("      margin-bottom: auto;\n");
      out.write("      background: #71f545;\n");
      out.write("      position: relative;\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: center;\n");
      out.write("      flex-direction: column;\n");
      out.write("      padding: 10px;\n");
      out.write("      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\n");
      out.write("      -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\n");
      out.write("      -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\n");
      out.write("      border-radius: 5px;\n");
      out.write("\n");
      out.write("    }\n");
      out.write("    .brand_logo_container {\n");
      out.write("      position: absolute;\n");
      out.write("      height: 170px;\n");
      out.write("      width: 170px;\n");
      out.write("      top: -75px;\n");
      out.write("      border-radius: 50%;\n");
      out.write("      background: #ffffff;\n");
      out.write("      padding: 10px;\n");
      out.write("      text-align: center;\n");
      out.write("    }\n");
      out.write("    .brand_logo {\n");
      out.write("      height: 150px;\n");
      out.write("      width: 150px;\n");
      out.write("      border-radius: 50%;\n");
      out.write("      border: 2px solid white;\n");
      out.write("    }\n");
      out.write("    .form_container {\n");
      out.write("      margin-top: 100px;\n");
      out.write("    }\n");
      out.write("    .login_btn {\n");
      out.write("      width: 100%;\n");
      out.write("      background: #1e6916 !important;\n");
      out.write("      color: white !important;\n");
      out.write("    }\n");
      out.write("    .login_btn:focus {\n");
      out.write("      box-shadow: none !important;\n");
      out.write("      outline: 0px !important;\n");
      out.write("    }\n");
      out.write("    .login_container {\n");
      out.write("      padding: 0 2rem;\n");
      out.write("    }\n");
      out.write("    .input-group-text {\n");
      out.write("      background: #1e6916 !important;\n");
      out.write("      color: white !important;\n");
      out.write("      border: 0 !important;\n");
      out.write("      border-radius: 0.25rem 0 0 0.25rem !important;\n");
      out.write("    }\n");
      out.write("    .input_user,\n");
      out.write("    .input_pass:focus {\n");
      out.write("      box-shadow: none !important;\n");
      out.write("      outline: 0px !important;\n");
      out.write("    }\n");
      out.write("    .custom-checkbox .custom-control-input:checked~.custom-control-label::before {\n");
      out.write("      background-color: #1e6916 !important;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("	h1{\n");
      out.write("	  color: #1e6916;\n");
      out.write("	  font-family: fantasy;\n");
      out.write("	  margin-top: 30px;\n");
      out.write("	  margin-left: -19%;\n");
      out.write("	}\n");
      out.write("    \n");
      out.write("    </style>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <div class=\"container h-100\">\n");
      out.write("      <div class=\"d-flex justify-content-center h-100\">\n");
      out.write("        <div class=\"user_card\">\n");
      out.write("          <div class=\"d-flex justify-content-center\">\n");
      out.write("            <div class=\"brand_logo_container\">\n");
      out.write("              <img src=\"/ArborVitae/img/homepage_images/logo.png\" class=\"brand_logo\" alt=\"Logo\">\n");
      out.write("              <h1>Bentornato</h1>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"d-flex justify-content-center form_container\">\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"get\">\n");
      out.write("              <div class=\"input-group mb-3\">\n");
      out.write("                <div class=\"input-group-append\">\n");
      out.write("                  <span class=\"input-group-text\"><i class=\"fas fa-user\"></i></span>\n");
      out.write("                </div>\n");
      out.write("                <!-- onchange=\"funzione di validazione javascript\" -->\n");
      out.write("                <input type=\"email\" name=\"email\" class=\"form-control input_user\" value=\"\" placeholder=\"email\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"input-group mb-2\">\n");
      out.write("                <div class=\"input-group-append\">\n");
      out.write("                  <span class=\"input-group-text\"><i class=\"fas fa-key\"></i></span>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"password\" name=\"password\" class=\"form-control input_pass\" value=\"\" placeholder=\"password\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"d-flex justify-content-center mt-3 login_container\">\n");
      out.write("              <button type=\"submit\" name=\"login\" class=\"btn login_btn\">Login</button>\n");
      out.write("             </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("      \n");
      out.write("          <div class=\"mt-4\">\n");
      out.write("            <div class=\"d-flex justify-content-center links\">\n");
      out.write("              Non hai un account? <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/signup.jsp\" class=\"ml-2\">Creane uno.</a>\n");
      out.write("            </div>\n");
      out.write("             ");
 if(session.getAttribute("logged")!=null && session.getAttribute("logged").equals("false")){
      out.write("\n");
      out.write("            	  <p class=\"pError\" >Email o password incorrette... Riprovare</p>\n");
      out.write("              ");
}session.removeAttribute("logged");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
