/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-07-07 10:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.dao.OrdersDao;
import model.dao.ProductsDao;
import java.util.ArrayList;
import model.bean.Orders;
import model.bean.Products;
import model.bean.ShoppingCart;
import model.dao.ShoppingCartDao;
import java.util.ArrayList;
import model.bean.Tree;

public final class ordini_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/../html/footer.html", Long.valueOf(1656400984000L));
    _jspx_dependants.put("/html/homeNavbar.jsp", Long.valueOf(1657099948000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.Tree");
    _jspx_imports_classes.add("model.bean.ShoppingCart");
    _jspx_imports_classes.add("model.bean.Products");
    _jspx_imports_classes.add("model.dao.ProductsDao");
    _jspx_imports_classes.add("model.dao.OrdersDao");
    _jspx_imports_classes.add("model.bean.Orders");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("model.dao.ShoppingCartDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"ISO-8859-1\">\n");
      out.write("		<title>Arbor Vitae</title>\n");
      out.write("		<link rel=\"icon\" href=\"/ArborVitae/img/homepage_images/logo.ico\" type=\"image/x-icon\">\n");
      out.write("		<link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("		<link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js\" rel=\"stylesheet\">\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/style/ordini.css\">\n");
      out.write("		<style>\n");
      out.write("		\n");
      out.write("		  /* <!--.separator{\n");
      out.write("		     border: 40px solid #F5F5F5;\n");
      out.write("		     background-color: #F5F5F5;\n");
      out.write("		   }*/\n");
      out.write("		p.info{\n");
      out.write("			display: inline; !important\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		   .cart-elements-count{\n");
      out.write("		   	bottom: 0px !important;\n");
      out.write("		   	top: 12px;\n");
      out.write("		   }\n");
      out.write("		</style>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>Arbor Vitae</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"/ArborVitae/style/homepage.css\">\n");
      out.write("  <style>\n");
      out.write("    .cart-button{\n");
      out.write("      border: none;\n");
      out.write("      background-color: white;\n");
      out.write("      padding: 0px !important;\n");
      out.write("    }\n");
      out.write("      \n");
      out.write("    .profile-button{\n");
      out.write("      border: none;\n");
      out.write("      background-color: white;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("   .dropbtn {\n");
      out.write("    background-color: none !important;\n");
      out.write("    color: white;\n");
      out.write("    padding: 8px;\n");
      out.write("    font-size: 10px;\n");
      out.write("    border: none;\n");
      out.write("    float: right;\n");
      out.write("    margin: -5px 0px 3px 0px;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown {\n");
      out.write("     position: relative;\n");
      out.write("     display: inline-block;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content {\n");
      out.write("     display: none;\n");
      out.write("     position: absolute;\n");
      out.write("     background-color: white;\n");
      out.write("     min-width: 160px;\n");
      out.write("     box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n");
      out.write("     z-index: 1;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content a {\n");
      out.write("     color: gray;\n");
      out.write("     padding: 3.5px;\n");
      out.write("     text-decoration: none;\n");
      out.write("     display: block;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .dropdown-content a:hover {background-color: #ddd; border-radius: 10px}\n");
      out.write("   \n");
      out.write("   .dropdown:hover .dropdown-content {display: block; border-radius: 10px}\n");
      out.write("   \n");
      out.write("   .dropdown:hover .dropbtn {background-color: #46dd2c; border-radius: 10px}\n");
      out.write("   \n");
      out.write("  </style>\n");
      out.write(" </head>\n");
      out.write(" \n");
      out.write(" <body>\n");
      out.write("  <header>\n");
      out.write("   <div class=\"logo\">\n");
      out.write("    <div class=\"navbar-item img-navbar-item\">\n");
      out.write("     <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/homepage_images/logo.png\" alt=\"Arbor Vitae's logo\" />\n");
      out.write("    </div>\n");
      out.write("    <div class=\"navbar-item\">\n");
      out.write("     <h1 class=\"site-title\"> Arbor Vitae</h1>\n");
      out.write("    </div>\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("   <input type=\"checkbox\" id=\"nav-toggle\" class=\"nav-toggle\">\n");
      out.write("   \n");
      out.write("   <nav>\n");
      out.write("   <div>\n");
      out.write("    <ul>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp\" class=\"link-elements\">Home</a></li>\n");
      out.write("    <li><a href=\"/ArborVitae/catalogoServlet?ordinamento=");
      out.print(1);
      out.write("\" class=\"link-elements\">Catalogo</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp#project\" class=\"link-elements\">Progetto</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp#aboutus\" class=\"link-elements\">Team</a></li>\n");
      out.write("    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/homepage.jsp#footer\" class=\"link-elements\">Contatti</a></li>\n");
      out.write("   \n");
      out.write("    \n");
      out.write("    ");
 if(request.getSession(false)==null || session.getAttribute("logged")==null || session.getAttribute("logged").equals("false")){
      out.write("\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/login.jsp\"><button type=\"button\" class=\"login-signup-buttons\">Login</button></a></li>\n");
      out.write("        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/signup.jsp\"><button type=\"button\" class=\"login-signup-buttons\">Sign Up</button></a></li>\n");
      out.write("       ");
}else{
      out.write("\n");
      out.write("        <li id=\"prev-count\"><a href=\"/ArborVitae/view/cart.jsp\"><button type=\"button\" class=\"cart-button\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/homepage_images/cart.png\" width=\"45px\" height= \"45px\"></button></a></li>\n");
      out.write("        ");
 ShoppingCartDao scd=new ShoppingCartDao();
         ShoppingCart sc= scd.doRetrieveByKey((String)session.getAttribute("email"));
         if(sc!=null){
          ArrayList<Tree> list= scd.doRetrieveTrees(sc.getcodeCart());
          if(list!=null){ 
           int x=list.size();
           if(x>0){
      out.write("\n");
      out.write("            <li><p class=\"cart-elements-count\" id=\"count\">");
      out.print(x);
      out.write("</p></li>\n");
      out.write("           ");
}
      out.write("\n");
      out.write("          ");
}
      out.write("\n");
      out.write("       ");
}
      out.write("\n");
      out.write("     <li><div class=\"dropdown\">\n");
      out.write("          \n");
      out.write("           <button type=\"button\" class=\"profile-button dropbtn\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/homepage_images/profile.png\" width=\"35px\" height=\"35px\">\n");
      out.write("            <div class=\"dropdown-content\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/ordini.jsp\">I miei Ordini</a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" >Log out</a>\n");
      out.write("        </div>\n");
      out.write("           </button>\n");
      out.write("      \n");
      out.write("         </div></li>\n");
      out.write("   ");
}
      out.write("\n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("   </div>\n");
      out.write("   </nav>\n");
      out.write("   \n");
      out.write("   <label for=\"nav-toggle\" class=\"nav-toggle-label\">\n");
      out.write("    <span></span>\n");
      out.write("   </label>\n");
      out.write("\n");
      out.write("  </header>\n");
      out.write(" </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("		\n");
      out.write("			<!-- <div class=\"separator\"><br></div>-->\n");
      out.write("		\n");
      out.write("		<section class=\"h-100 gradient-custom\">\n");
      out.write("	  <div class=\"container py-5 h-100\">\n");
      out.write("	  <br><br><br><br>\n");
      out.write("	    <div class=\"row d-flex justify-content-center align-items-center h-100\">\n");
      out.write("	      <div class=\"col-lg-8 col-xl-10\">\n");
      out.write("	        <div class=\"card\" style=\"border-radius: 10px;\"></div>\n");
      out.write("	          <div class=\"card-header px-4 py-5\">\n");
      out.write("	            <h5 class=\"text-muted mb-0\">I miei ordini</h5>\n");
      out.write("	          </div>\n");
      out.write("	      	<script>\n");
      out.write("			function redCert(x){\n");
      out.write("				window.location.replace(\"http://localhost:8080/ArborVitae/view/attestati.jsp?treeName=\"+encodeURIComponent(x));\n");
      out.write("			}\n");
      out.write("	              									\n");
      out.write("	              									\n");
      out.write("	        </script>\n");
      out.write("	        \n");
      out.write("	            ");
String email= (String)session.getAttribute("email");
	              OrdersDao oD= new OrdersDao();
	              ArrayList<Orders> orderList = oD.doRetrieveByKey(email);
	              if(orderList.size()==0){
      out.write("\n");
      out.write("	              	<div class=\"card-body p-4\">\n");
      out.write("	            		<div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("	            	   		<p class=\"lead fw-normal mb-0\" style=\"color: #46dd2c;\">Non hai effettuato alcun ordine fino ad ora</p>	\n");
      out.write("	            		</div>\n");
      out.write("	            	</div>\n");
      out.write("	              ");
}else{
	              	int i=0;
	              	int j=0;
	              	ProductsDao pD = new ProductsDao();
	              	for(i=0;i<orderList.size();i++){
	              		Orders currOrder = orderList.get(i);
	              		ArrayList<Products> currProdList = pD.doRetrieveByKey(orderList.get(i).getCodeOrder());
      out.write("\n");
      out.write("	              		<div class=\"card-body p-4\">\n");
      out.write("            				<div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("      						<p class=\"lead fw-normal mb-0\" style=\"color: #46dd2c;\">Data: ");
      out.print( currOrder.getDate().toString() );
      out.write("</p>\n");
      out.write("    					</div>\n");
      out.write("	              		");
for(j=0;j<currProdList.size();j++){
	              			Products currProd= currProdList.get(j);
      out.write("\n");
      out.write("	            					<div class=\"card shadow border mb-4\">\n");
      out.write("	              						<div class=\"card-body\">\n");
      out.write("	              							<div>\n");
      out.write("	              								<button id=\"certButton\" onclick= \"redCert('");
      out.print(currProd.getName());
      out.write("')\">Ottieni Certificato</button>\n");
      out.write("	              								\n");
      out.write("	              		\n");
      out.write("	              									\n");
      out.write("	              							</div>\n");
      out.write("	               							<div class=\"row\">\n");
      out.write("	                  							<div class=\"col-md-2 img-wid\">\n");
      out.write("	                    							<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/trees_img/");
      out.print(currProd.getName().toLowerCase());
      out.write("1.jpg\" class=\"img-fluid\" alt=\"name tree\">\n");
      out.write("	                  							</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"info\">Nome</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"info\">Paese</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"info\">Co2</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"info\">Quantit&agrave;</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"info\">Prezzo Totale</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"infoDesc\"></p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"infoDesc\">");
      out.print(currProd.getName());
      out.write("</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"infoDesc\">");
      out.print(currProd.getCountry());
      out.write("</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"infoDesc\">");
      out.print(currProd.getCo2());
      out.write("</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"infoDesc\">");
      out.print(currProd.getQuantity());
      out.write("</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                  						<div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    						<p class=\"infoDesc\">");
      out.print(String.format("%.2f", currProd.getPrice()*currProd.getQuantity()).replace(',', '.'));
      out.write(" &euro;</p>\n");
      out.write("	                  						</div>\n");
      out.write("	                					</div>\n");
      out.write("	              					</div>\n");
      out.write("		        				</div>\n");
      out.write("	              		");
}
      out.write("\n");
      out.write("	        	      	\n");
      out.write("       					<hr class=\"mb-4\" style=\"background-color: #46dd2c ; opacity: 1;\">\n");
      out.write("     					</div>\n");
      out.write("     					");
}	
	         		}
      out.write("\n");
      out.write("	           	\n");
      out.write("	              <!--<p class=\"lead fw-normal mb-0\" style=\"color: #46dd2c;\">Ricevute</p>\n");
      out.write("	            </div>\n");
      out.write("	            <div class=\"card shadow border mb-4\">\n");
      out.write("	              <div class=\"card-body\">\n");
      out.write("	                <div class=\"row\">\n");
      out.write("	                  <div class=\"col-md-2 img-wid\">\n");
      out.write("	                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/trees_img/anacardo1.png\"\n");
      out.write("	                      class=\"img-fluid\" alt=\"name tree\">\n");
      out.write("	                  </div>\n");
      out.write("	                  <div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    <p class=\"info\">Paese</p>\n");
      out.write("	                  </div>\n");
      out.write("	                  <div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    <p class=\"info\">co2</p>\n");
      out.write("	                  </div>\n");
      out.write("	                  <div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    <p class=\"info\">1</p>\n");
      out.write("	                  </div>\n");
      out.write("	                  <div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    <p class=\"info\">prezzo</p>\n");
      out.write("	                  </div>\n");
      out.write("	                  <div class=\"col-md-2 text-center d-flex justify-content-center align-items-center\">\n");
      out.write("	                    <p class=\"info\">Nome</p>\n");
      out.write("	                  </div>\n");
      out.write("	                </div>\n");
      out.write("	              </div>\n");
      out.write("		        </div>\n");
      out.write("		        \n");
      out.write("		          \n");
      out.write("	            <hr class=\"mb-4\" style=\"background-color: #46dd2c ; opacity: 1;\">\n");
      out.write("		\n");
      out.write("		      </div>\n");
      out.write("		    </div>\n");
      out.write("		    </div>\n");
      out.write("		    </div>\n");
      out.write("		  </div>-->\n");
      out.write("		</section>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("   <div id=\"footer\" >\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>Footer</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../style/homepage.css\">\n");
      out.write("  <style>\n");
      out.write("   .container9{\n");
      out.write("     background-color: #F5F5F5;\n");
      out.write("     text-align: center;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   h6{\n");
      out.write("     font-family: 'Work Sans', sans-serif;\n");
      out.write("     font-weight: 400;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("      \n");
      out.write("   .footer-text{\n");
      out.write("     border: 3px solid #46dd2c;\n");
      out.write("     background-color: #46dd2c;\n");
      out.write("     text-align: center;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .info-container {\n");
      out.write("     display: grid;\n");
      out.write("        grid-template-columns: repeat(3, 1fr);\n");
      out.write("     grid-template-rows: 1fr;\n");
      out.write("     grid-column-gap: 50px;\n");
      out.write("     grid-row-gap: 0px;\n");
      out.write("     padding: 1em;\n");
      out.write("   }\n");
      out.write("    \n");
      out.write("   .item1 { grid-area: 1 / 1 / 2 / 2; background: white; border-radius: 20px; outline: 2px solid #46dd2c; font-size: 25px}\n");
      out.write("   .item2 { grid-area: 1 / 2 / 2 / 3; background:  white; border-radius: 20px; outline: 2px solid #46dd2c; font-size: 25px}\n");
      out.write("   .item3 { grid-area: 1 / 3 / 2 / 4; background: white; border-radius: 20px; outline: 2px solid #46dd2c; font-size: 25px}\n");
      out.write("    \n");
      out.write("   .item1,.item2,.item3 {padding: 0rem;}\n");
      out.write("   \n");
      out.write("   ul {\n");
      out.write("     display: block;\n");
      out.write("     list-style-type: none;\n");
      out.write("     margin: 0;\n");
      out.write("     padding: 0;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .social-container {\n");
      out.write("     display: grid;\n");
      out.write("     grid-template-columns: repeat(4, 1fr);\n");
      out.write("     grid-template-rows: 0fr;\n");
      out.write("     grid-column-gap: 5px;\n");
      out.write("     grid-row-gap: 0px;\n");
      out.write("     padding: 1em;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   .footer-div-copyright {\n");
      out.write("     border: 15px solid #46dd2c;\n");
      out.write("     background-color: #46dd2c;\n");
      out.write("     text-align: center;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   h8{\n");
      out.write("    font-size: 25px;\n");
      out.write("    color: white;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("   h9{\n");
      out.write("    font-size: 25px;\n");
      out.write("    color: #46dd2c;\n");
      out.write("   }\n");
      out.write("   \n");
      out.write("  </style>\n");
      out.write(" </head>\n");
      out.write(" \n");
      out.write(" <body>\n");
      out.write("  <footer>\n");
      out.write("     <!-- Sezione Testo fine pagina //metti uno spazio sotto-->\n");
      out.write("       <div  class=\"footer-text\">\n");
      out.write("         <p>\n");
      out.write("    <h8>Per qualsiasi informazione e soprattutto se vorresti diventare membro del team non esitare a contattarci!<h8>\n");
      out.write("         </p>\n");
      out.write("       </div>\n");
      out.write("     <!-- Grid container -->\n");
      out.write("       <div class=\"container9\">\n");
      out.write("    <br>   \n");
      out.write("       <!-- Contatti -->\n");
      out.write("        <div class=\"info-container\">\n");
      out.write("      <div class=\"item1\">\n");
      out.write("       <h9><br>Indirizzo</h9>\n");
      out.write("      <ul>\n");
      out.write("       <li>\n");
      out.write("        <h6> Universit&agrave; degli Studi di Salerno <br> Via Giovanni Paolo II, 132 </br>84084 Fisciano (SA)</h6>\n");
      out.write("       </li>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"item2\">\n");
      out.write("       <h9><br>E-mail</h9>\n");
      out.write("      <ul>\n");
      out.write("       <li>\n");
      out.write("        <h6>c.sorrentino82@studenti.unisa.it</h6>\n");
      out.write("       </li>\n");
      out.write("      <li>\n");
      out.write("       <h6>m.colella20@studenti.unisa.it</h6>\n");
      out.write("      </li>\n");
      out.write("      <li>\n");
      out.write("       <h6>f.monzillo2@studenti.unisa.it</h6>\n");
      out.write("      </li>\n");
      out.write("      </ul>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"item3\">\n");
      out.write("       <h9><br>Telefono</h9>\n");
      out.write("      <ul>\n");
      out.write("       <li>\n");
      out.write("        <h6>+39 334 709 0726</h6>\n");
      out.write("       </li>\n");
      out.write("       <li>\n");
      out.write("        <h6>+39 392 399 0242</h6>\n");
      out.write("       </li>\n");
      out.write("       <li>\n");
      out.write("        <h6>+39 342 779 7976</h6>\n");
      out.write("       </li>\n");
      out.write("      </ul>\n");
      out.write("      </div>\n");
      out.write("     </div>\n");
      out.write("  \n");
      out.write("      <!-- Sezione Social media -->\n");
      out.write("          <div class=\"social-container\">\n");
      out.write("           <!-- Facebook -->\n");
      out.write("             <a href=\"#!\"><img src=\"../img/homepage_images/facebooklogo.png\" height=\"30\"></a>\n");
      out.write("\n");
      out.write("           <!-- Twitter -->\n");
      out.write("             <a href=\"#!\"><img src=\"../img/homepage_images/twitter.png\" height=\"30\"></a>\n");
      out.write("\n");
      out.write("           <!-- Google -->\n");
      out.write("             <a href=\"#!\" role=\"button\"><img src=\"../img/homepage_images/google.png\" height=\"30\"></a>\n");
      out.write("\n");
      out.write("           <!-- Instagram -->\n");
      out.write("             <a href=\"#!\"><img src=\"../img/homepage_images/instagram-logo-tumb.png\" height=\"30\"></a>\n");
      out.write("           </div>\n");
      out.write("     </div>\n");
      out.write("  \n");
      out.write("   <div class=\"footer-div-copyright\">\n");
      out.write("    @Arbor_Vitae_2022\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("  </footer>\n");
      out.write("\n");
      out.write(" </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("   </div>\n");
      out.write("		\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
